language: java

jdk:
  - oraclejdk8

cache:
 directories:
 - $HOME/.gradle/caches/
 - $HOME/.gradle/wrapper/

env:
  global:
    - GRADLE_OPTS="-Xms128m"

install: echo "skip 'gradle assemble' step"
script: gradle build --continue

after_success:
  - gradle jacocoTestReport coveralls